### ISSUE TITLE
Cannot install kdeploy because of permission denied.

### ISSUE THREAD

**Issue by LiarOnce** [AdrianMachado/KaiUI#27]
**Describe the bug**
When I tried to initialize, `npm install` output this error:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/kaiostech/kdeploy.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '13.229.188.59' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: 无法读取远程仓库。(Unable to read remote repository.)
npm ERR! 
npm ERR! 请确认您有正确的访问权限并且仓库存在。(Please make sure you have the correct access rights and the repository exists.)
npm ERR! 
npm ERR! exited with error code: 128
```
Can I need to remove `kdeploy` from `package.json`?

**To Reproduce**
1. `git clone (URL)`
2. `cd KaiUI`
3. `npm install`

**Browser/Emulator (please complete the following information):**
 - OS: Windows 10/Manjaro Linux
 - Browser: Pale Moon/Kaiosrt
 - Version: 28.6.1/Sep19

**Comment by inovramadani** [comment]
I hit same error when do initial npm install.

![image](https://user-images.githubusercontent.com/27492820/74297954-fc273c00-4d7a-11ea-9ff6-e6085be19497.png)

I can install if I remove kdeploy from devDependencies and the scripts related to it.
