### ISSUE TITLE
Difficult for newbie

### ISSUE THREAD

**Issue by ctuxboy** [AdrianMachado/KaiUI#6]
Hello,

Trying understand your awesome KaiUI, but for me as newbie it is difficult to understand how all this works.
Thats also the problem on the Developer KaiOSTech docs, it is very confused and hard to understand, how all the things works. Reading the last week the docs in KaiOSTech for understanding, but the lack off clear explanation is a real disaster.

I know what npm is, but at the moment download your KaiUI manually, when unzip and click on index.html nothing shows up, when looking to index.html source code, see links that not 'connected' to the 'src' files. Maybe this works when instal with npm, but for newbie developers/hobbyist don't use all this modern technics and trying buidling a 'simple' app for KaiOS it is not the most easy UI.
Maybe adding some examples is better to understand.
But i hope you understand, your help and trying making a better app-dev experience is really good, but not for everyone that trying to start understandable how app-dev works for KAiOS.
The missing thing for KAiOS, is good up-to-date understandable docs for the beginner.

**Comment by AdrianMachado** [comment]
Hello Christophe,

I completely agree with you that it is not clear on how to use KaiUI. Honestly it isn't in a very usable state right now because a lot of feature work is ongoing. I will try to make a more clear guide on how to use the demo app in the immediate future, however an installation guide will be provided in the future once feature work wraps up.

Feel free to email me to get an understanding about how to get the demo app running.

- Adrian

**Comment by ctuxboy** [comment]
Hi Adrian,
First off all, nice work man!
You do it really good with this project, i knwo that more intermeddiate developers understand your work with ease, but i'm also a beginner with JS, so i'm a little stupid and the moment for understand a lot ;-)

I don't want to be critical, i say this only for help.
I think a gamechanger is making real examples, with some code snippets or so...
My opinion, when KaiOS, makes better docs, with real examples, more devs interesting in this OS, also in the Western world. I have a lot off ideas building useful apps for this OS, there is a market for this and not only in the development regions. I'm a heavy smartphone user, but i really love this OS, and hope it planned a lot of updates in the future. It's hard missing my smartphone, but i try it ;-)

PS: sorry about my poor english :-/

Regards,
Christophe

**Comment by AdrianMachado** [comment]
Don't apologize for having poor English, I getcha loud and clear. KaiOS recently updated their documentation with some examples that you might find good to learn from: https://developer.kaiostech.com/getting-started/build-your-first-app/sample-code

**Comment by ctuxboy** [comment]
Oeif! Okay :-)
yes, i know, do my little first steps following the docs on KaiOS :-)
